def generate_candidate_profile() -> dict:
    """
    Generate candidate profile from resume.

    Later, this can be replaced with PDF/DOCX parsing so the profile is created
    dynamically from an uploaded resume. For now, this is generated from the
    extracted resume data.
    """
    return {
        "preferred_titles": [
            "frontend software engineer",
            "software engineer - frontend",
            "frontend developer",
            "front end developer",
            "angular developer",
            "react developer",
            "ui developer",
            "ui engineer",
            "software engineer",
        ],
        "preferred_skills": [
            "angular",
            "angular 17",
            "rxjs",
            "ngrx",
            "react",
            "react.js",
            "redux",
            "flutter",
            "dart",
            "typescript",
            "javascript",
            "html",
            "html5",
            "css",
            "css3",
            "rest api",
            "restful api",
            "graphql",
            "jwt",
            "rbac",
            "angular material",
            "primeng",
            "bootstrap",
            "material-ui",
            "material ui",
            "jasmine",
            "karma",
            "jest",
            "git",
            "jenkins",
            "azure devops",
            "azure",
            "jira",
            "agile",
            "scrum",
            "responsive design",
            "unit testing",
        ],
        "preferred_locations": {
            "country": "india",
            "accept_remote": True,
            "india_cities": [
                "agra",
                "bangalore",
                "bengaluru",
                "hyderabad",
                "pune",
                "gurgaon",
                "gurugram",
                "noida",
                "delhi",
                "mumbai",
                "chennai",
                "kolkata",
                "ahmedabad",
                "kochi",
                "trivandrum",
                "coimbatore",
                "indore",
                "jaipur",
                "lucknow",
                "nagpur",
            ],
        },
        "experience_years": 5,
        "negative_keywords": [
            "senior manager",
            "engineering manager",
            "director",
            "principal",
            "staff engineer",
            "architect",
            "intern",
            "fresher",
            "qa tester",
            "manual testing",
            "sales",
            "marketing",
            "recruiter",
            "trainer",
            "data scientist",
            "data analyst",
            "devops engineer",
            "backend engineer",
        ],
    }


TARGET_PROFILE = generate_candidate_profile()